name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Get packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Knip
        run: npm run knip

      - name: Dependencies
        run: npm run dependencies:ci

      - name: Test
        run: npm test
        env:
          TZ: Europe/Berlin
